### ISSUE TITLE
Empty setup.py

### ISSUE THREAD

**Issue by samfux84** [wjidea/defusion#1]
Hi,

How can defusion be installed if the setup.py file is empty ?

[sfux@eu-c7-041-01 defusion]$ ls -ltr setup.py 
-rw-r--r-- 1 sfux T0000 0 Nov 16 09:54 setup.py

Also running make results in an error:

[sfux@eu-c7-041-01 defusion]$ make
Makefile:2: *** missing separator.  Stop.

**Comment by wjidea** [comment]
Hi,
Sorry for the late response. For the moment, I upload deFusion to pip so I didn't prepare defusion as a package. Instead, I would encourage you adding deFusion folder to your path and run those 1-5 steps accordingly. I prepared a tutorial here https://wjidea.github.io/defusion/tutorial.html to help you walk through the analysis. Let me know if you encounter any other issues.
Thanks,

Jie

**Comment by samfux84** [comment]
Thank you for your reply.

I will send the instructions to our users that requested the installation of deFusion.
